name: Run Test Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    # Cancel in-progress runs when a new commit is pushed
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        # Make sure uv is in the path
        export PATH="$HOME/.cargo/bin:$PATH"
        # Check if uv is installed correctly
        which uv || echo "uv not found in PATH"
        
        # Create a virtual environment with uv
        uv venv
        
        # Install TensorFlow and other dependencies using uv
        if [ -f requirements.txt ]; then 
          uv pip install -r requirements.txt --system || pip install -r requirements.txt
        fi
        # Install the package in development mode to make all modules available
        uv pip install -e . --system || pip install -e .
        
    - name: List installed packages
      run: |
        # Try uv first, fall back to pip
        uv pip list --system || pip list
        
    - name: Run test_integration.py
      env:
        CUDA_VISIBLE_DEVICES: "-1"  # Ensure GPU is disabled
        TF_CPP_MIN_LOG_LEVEL: "2"   # Reduce TensorFlow logging
      run: |
        cd yukawas
        # Print directory contents for debugging
        ls -la
        # Run with error output
        python test_integration_model13.py -1.00300101533232333 'end' 'alltiny' || { echo "Command failed with exit code $?"; exit 1; }
      timeout-minutes: 10  # Set a timeout to prevent long-running tests 

    - name: run Model_13_Do.py
      env:
        CUDA_VISIBLE_DEVICES: "-1"  # Ensure GPU is disabled
        TF_CPP_MIN_LOG_LEVEL: "2"   # Reduce TensorFlow logging
      run: |
        cd yukawas
        python Model_13_Do.py -1.2324123412 'phi' 'alltiny' 'skipnone' 'eager' || { echo "Command failed with exit code $?"; exit 1; }
      timeout-minutes: 30  # Set a timeout to prevent long-running tests 
