name: Run Test Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        # Install TensorFlow and other dependencies using uv
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
        # Install the package in development mode to make all modules available
        uv pip install -e .
        
    - name: List installed packages
      run: uv pip list
        
    - name: Run test_integration.py
      env:
        CUDA_VISIBLE_DEVICES: "-1"  # Ensure GPU is disabled
        TF_CPP_MIN_LOG_LEVEL: "2"   # Reduce TensorFlow logging
      run: |
        cd yukawas
        python test_integration.py -1.00300101533232333 'end' 'alltiny'
      timeout-minutes: 30  # Set a timeout to prevent long-running tests 